version: '3.8'

services:
  app:
    build: .
    env_file: ./.env
    environment:
      - GITHUB_PRIVATE_KEY_FILE=./.private.key
    restart: unless-stopped
    volumes:
      - data:/usr/app/data/
      - ./.private.key:/usr/app/.private.key

volumes:
  data: